In [70]:
import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeRegressor ,DecisionTreeClassifier
from sklearn.model_selection import train_test_split,RandomizedSearchCV,GridSearchCV
from sklearn.metrics import mean_absolute_error ,r2_score,mean_squared_error 

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')


In [38]:
df=pd.read_csv("iris.csv")

In [39]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [41]:
df.drop("Id",axis=1,inplace=True)

In [42]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [43]:
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [44]:
df['Species'].unique

<bound method Series.unique of 0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object>

In [45]:
df['Species']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [46]:
df['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [47]:
df['Species'].replace({"Iris-setosa":1,"Iris-versicolor": 2,"Iris-virginica":3},inplace=True)

In [48]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        1
1              4.9           3.0            1.4           0.2        1
2              4.7           3.2            1.3           0.2        1
3              4.6           3.1            1.5           0.2        1
4              5.0           3.6            1.4           0.2        1
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        3
146            6.3           2.5            5.0           1.9        3
147            6.5           3.0            5.2           2.0        3
148            6.2           3.4            5.4           2.3        3
149            5.9           3.0            5.1           1.8        3

[150 rows x 5 columns]

In [50]:
x=df.drop('SepalLengthCm',axis=1)
y=df['SepalLengthCm']

In [51]:
x

SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0             3.5            1.4           0.2        1
1             3.0            1.4           0.2        1
2             3.2            1.3           0.2        1
3             3.1            1.5           0.2        1
4             3.6            1.4           0.2        1
..            ...            ...           ...      ...
145           3.0            5.2           2.3        3
146           2.5            5.0           1.9        3
147           3.0            5.2           2.0        3
148           3.4            5.4           2.3        3
149           3.0            5.1           1.8        3

[150 rows x 4 columns]

In [52]:
y

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

# Train test split

In [53]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [54]:
x_train

SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
22            3.6            1.0           0.2        1
15            4.4            1.5           0.4        1
65            3.1            4.4           1.4        2
11            3.4            1.6           0.2        1
42            3.2            1.3           0.2        1
..            ...            ...           ...      ...
71            2.8            4.0           1.3        2
106           2.5            4.5           1.7        3
14            4.0            1.2           0.2        1
92            2.6            4.0           1.2        2
102           3.0            5.9           2.1        3

[120 rows x 4 columns]

In [55]:
dt_reg=DecisionTreeRegressor()
dt_reg

DecisionTreeRegressor()

In [56]:
dt_reg.fit(x_train,y_train)

DecisionTreeRegressor()

# model testing

In [61]:
y_pred=dt_reg.predict(x_test)
y_pred[5:10]

array([4.6, 5.2, 5.9, 6.3, 5.5])

In [60]:
y_test[5:10]

31     5.4
64     5.6
141    6.9
68     6.2
82     5.8
Name: SepalLengthCm, dtype: float64

# evaluation

In [63]:
# testing data accuaracy
y_pred=dt_reg.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
print("the value of mse is",mse)
print("*"*50)
rmse=np.sqrt(mse)
print("the value of rmse is",rmse)
print("*"*50)
r2_value=r2_score(y_test,y_pred)
print("the value of r2_value is",r2_value)

the value of mse is 0.2524166666666667
**************************************************
the value of rmse is 0.5024108544474997
**************************************************
the value of r2_value is 0.6343200695383429


In [64]:
# training data accuaracy
y_pred_train=dt_reg.predict(x_train)

mse=mean_squared_error(y_train,y_pred_train)
print("the value of mse is",mse)
print("*"*50)
rmse=np.sqrt(mse)
print("the value of rmse is",rmse)
print("*"*50)
r2_value=r2_score(y_train,y_pred_train)
print("the value of r2_value is",r2_value)

the value of mse is 0.0007916666666666655
**************************************************
the value of rmse is 0.028136571693556864
**************************************************
the value of r2_value is 0.9988236738728681


# Hyperparameter Tuninig

In [ ]:
dt_reg=DecisionTreeRegressor(splitter='best')


In [78]:
hyperpara={"criterion":['mse',"mae"],
    "splitter": ["best", "random"],
    "max_depth": np.arange(1,8),
    "min_samples_split": np.arange(1,10),
    "min_samples_leaf": np.arange(1,5)}
gscv=GridSearchCV(dt_reg,hyperpara,cv=5)
gscv.fit(x_train,y_train)
gscv.best_estimator_

DecisionTreeRegressor(max_depth=5, min_samples_leaf=3, min_samples_split=8,
                      splitter='random')

In [86]:
dt_reg=DecisionTreeRegressor(max_depth=5, min_samples_leaf=3, min_samples_split=8,splitter='random')
dt_reg.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=5, min_samples_leaf=3, min_samples_split=8,
                      splitter='random')

In [91]:
# testing data accuaracy
y_pred=dt_reg.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
print("the value of mse is",mse)
print("*"*50)
rmse=np.sqrt(mse)
print("the value of rmse is",rmse)
print("*"*50)
r2_value=r2_score(y_test,y_pred)
print("the value of r2_value is",r2_value)

the value of mse is 0.13783530958557746
**************************************************
the value of rmse is 0.3712617803997302
**************************************************
the value of r2_value is 0.8003158543766987


In [92]:
# training data accuaracy
y_pred_train=dt_reg.predict(x_train)

mse=mean_squared_error(y_train,y_pred_train)
print("the value of mse is",mse)
print("*"*50)
rmse=np.sqrt(mse)
print("the value of rmse is",rmse)
print("*"*50)
r2_value=r2_score(y_train,y_pred_train)
print("the value of r2_value is",r2_value)

the value of mse is 0.10756955691367459
**************************************************
the value of rmse is 0.32797798236112524
**************************************************
the value of r2_value is 0.8401639406969718


In [65]:
import pickle

In [94]:
with open ("dt_regressor.pkl","wb") as f:
    pickle.dump(dt_reg,f)

In [96]:
import json
project_data={"columns":list(x.columns)}

In [98]:
with open ("project_data.json","w") as f:
    json.dump(project_data,f)

In [99]:
project_data

{'columns': ['SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']}

In [104]:
SepalWidthCm = 2.5
PetalLengthCm =2.6
PetalWidthCm =2.8
Species = 1

In [105]:
test_array=np.zeros(4)
test_array

array([0., 0., 0., 0.])

In [106]:
test_array[0]=SepalWidthCm
test_array[1]=PetalLengthCm
test_array[2]=PetalWidthCm
test_array[3]=Species

In [107]:
test_array

array([2.5, 2.6, 2.8, 1. ])

In [109]:
dt_reg.predict([test_array])

array([5.16])